---
- name: Bootstrap ssh keys
  # This does the setup of the user rcpaffenroth and makes sure everything
  # is current for them.  
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove the old ssh directory, if there is one
      ansible.builtin.file:
        path: /home/rcpaffenroth/.ssh
        state: absent
    - name: Get the ssh directory    
      ansible.builtin.git:
        repo: 'rcpaffenroth@moc-gateway.rcpaffenroth.org:repos/ssh.git'
        dest: /home/rcpaffenroth/.ssh
        update: yes
    - name: Make sure the ssh directory is owned by rcpaffenroth
      ansible.builtin.file:
        path: /home/rcpaffenroth/.ssh
        owner: rcpaffenroth
        group: rcpaffenroth
        mode: '700'
        recurse: yes