---
- name: Bootstrap ssh keys
  # This does the setup of the user rcpaffenroth and makes sure everything
  # is current for then.  Note, this does not require root.
  hosts: localhost
  gather_facts: false
  become: true
  become_user: rcpaffenroth
  tasks:
    - name: Get the ssh directory    
      ansible.builtin.git:
        repo: 'rcpaffenroth@moc-gateway.rcpaffenroth.org:repos/ssh.git'
        dest: $HOME/ssh
        update: yes

    - name: Copy the ssh directory
      ansible.builtin.copy:
        src: $HOME/ssh
        dest: $HOME/.ssh
        owner: rcpaffenroth
        group: rcpaffenroth
        mode: "700"
        force: yes
        