---
- name: Bootstrap ssh keys
  # This does the setup of the user rcpaffenroth and makes sure everything
  # is current for them.  
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get the ssh directory    
      ansible.builtin.git:
        repo: 'rcpaffenroth@moc-gateway.rcpaffenroth.org:repos/ssh.git'
        dest: $HOME/ssh
        update: yes
    - name: Copy the ssh directory
      ansible.builtin.copy:
        # NOTE, this is $HOME for root
        remote_src: yes
        src: $HOME/ssh
        dest: /home/rcpaffenroth/.ssh
        owner: rcpaffenroth
        group: rcpaffenroth
        mode: "700"
        force: yes
