---
- name: Bootstrap ssh keys
  # This does the setup of the user rcpaffenroth and makes sure everything
  # is current for then.  Note, this does not require root.
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Get ssh
      git:
        repo: rcpaffenroth@moc-gateway.rcpaffenroth.org:repos/ssh.git
        dest: ssh
        accept_hostkey: yes
        update: yes

    - name: Tell the user what to do next...
      ansible.builtin.debug:
        msg:
          - "You now have an ssh directory"
          - "You should copy this to .ssh"
